apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::419724900115:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::419724900115:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-138LVXGWHEN6X
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-26T08:56:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1169"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 00e1661d-bdd6-45ec-973c-dc1f715a391a
